---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: total hack
      shell: rm -rf /var/lib/apt/lists/*

    - name: Install docker
      shell: "curl -fsSL https://get.docker.com/ | bash"
      
    - name: Copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777        

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Install docker-compose
      apt:
        name: docker-compose

    - name: Start docker containers (could take 30min)
      shell: bash /storage/docker/docker/dockercomposescript.sh
      args:
        chdir: /storage/docker
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0
      tags:
        - startcontainers

    - name: Copy docker systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockerhack.service
        dest: /etc/systemd/system
      tags:
        - dockerservices

    - name: Enable docker-hack systemd service
      systemd:
        name: dockerhack
        enabled: yes
      tags:
        - hack
        - dockerservices

    - name: Copy docker-compose systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockercompose.service
        dest: /etc/systemd/system
      tags:
        - dockercompose
        - dockerservices

    - name: Enable docker-compose systemd service
      systemd:
        name: dockercompose
        enabled: yes
      tags:
        - hack
        - dockerservices
