---
- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Grab docker containers from groups vars
      set_fact: dockercontainers="{{ hostvars[\"raspberrypi\"][\"DOCKER\"] }}"
      tags:
        - dockercomposeconfig
  
    - name: Copy docker-compose.yml to pi
      template:
        src: docker-compose-complete-jinja.yml
        dest: /storage/docker/docker-compose.yml
        owner: nobody
        group: nogroup
        mode: 0777  
        force: yes 
      vars:
        dockerKitchenSink: false
        docker: "{{ dockercontainers }}"
      tags:
        - dockercomposeconfig

    - name: Copy kitchen sink docker-compose.yml to pi
      template:
        src: docker-compose-complete-jinja.yml
        dest: /storage/docker/docker-compose-kitchensink.yml
        owner: nobody
        group: nogroup
        mode: 0777  
        force: yes 
      vars:
        dockerKitchenSink: true 

      tags:
        - dockercomposeconfig

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Install docker-compose
      apt:
        name: docker-compose

    - name: Start docker containers (could take 30min)
      shell: bash /storage/docker/docker/dockercomposescript.sh
      args:
        chdir: /storage/docker
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0
      tags:
        - startcontainers

    - name: Copy docker systemd files
      copy:
        remote_src: yes
        src: /storage/docker/docker/dockerhack.service
        dest: /etc/systemd/system
      tags:
        - dockerservices

    - name: Enable docker-hack systemd service
      systemd:
        name: dockerhack
        enabled: yes
        state: started
      tags:
        - hack
        - dockerservices


