---
- name: Install docker Ansible prerequisite on control ubuntu PC
  hosts: localhost
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{item}}"
      with_items:
        - python-pip
          
    - name: Install python docker
      pip:
        name: "{{item}}"
        version: "1.9.0"
        state: forcereinstall
      with_items:
        - docker-py
        - docker-compose

    - name: Install pyyaml
      pip:
        name: pyYAML

- name: Docker containers
  hosts: raspberrypis
  become: true
  tasks:
    - name: Copy docker install script
      copy:
        src: files/apt-docker/get-docker.sh
        dest: /tmp/get-docker.sh
        mode: 0777

    - name: Run docker install script
      command: /tmp/get-docker.sh

    #- name: remove docker install script
    #  file:
    #    path: /tmp/get-docker.sh
    #    state: absent

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Allow guest access to samba share
      file:
        path: /storage
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/public folder
      file:
        path: /storage/public
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: create /storage/docker directory
      file:
        path: /storage/docker
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: Copy docker-compose.yml to pi
      copy:
        src: docker-compose.yml
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777        
      tags:
        - dockercompose

    - name: Copy files
      copy:
        src: files/
        dest: /storage/docker
        owner: nobody
        group: nogroup
        mode: 0777
      tags:
        - dockercompose

    - name: phpmyadmin permission issue
      file:
        path: /storage/docker/phpmyadmin/config.inc.php
        mode: 0774

    - name: Copy docker-compose systemd service
      copy:
        src: files/systemd/docker-compose.service
        dest: /etc/systemd/system

    - name: Copy docker systemd service
      copy:
        src: files/docker/docker.service
        dest: /etc/systemd/system    

    - name: Enable docker systemd service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Check docker status
      shell: /usr/bin/env docker version

    - name: Start docker containers
      shell: docker-compose up -d
      args:
        chdir: /storage/docker
      tags:
        - startdockercontainers



    - name: Enable docker-compose systemd service
      systemd:
        name: docker-compose
        enabled: yes




