---
- name: Jupyter and tensorflow and Julia
  hosts: raspberrypis
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Julia
      apt: 
        name: "{{item}}"
      with_items:
        - julia
        - libzmq3-dev
        - python3-zmq

    - name: Install Jupyter
      pip:
        executable: pip3
        name: jupyter

    - name: Install IJulia
      shell: |
        julia -e 'Pkg.add("IJulia");'

    - name: Copy systemd for jupyter-notebook
      copy:
        src: files/systemd/jupyter.service
        dest: /etc/systemd/system

    - name: create notebooks directory
      file:
        path: /storage/docker/jupyter/notebooks
        mode: 0777

    - name: start and enable jupyter
      systemd:
        name: jupyter
        enabled: yes
        state: started










