---
- name: Install Jupyter 
  hosts: raspberrypis
  become: true
  tasks:
    #- name: Fix broken packages
    #  shell: apt-get -y -f install

    #- name: Install Julia
    #  apt: 
    #    name: "{{item}}"
    #  with_items:
    #    - julia
    #    - libzmq3-dev
    #    - python3-zmq
    #    - "r-base"
    #    - "libssl-dev"
    #    - "python-seaborn" 
    #    - "python-pandas"
    #    - "python-matplotlib"
    #    - "ttf-bitstream-vera"
    #    - "python-ipykernel"
    #    - "python3-ipykernel"
    #  retries: 2
    #  register: result
    #  until: result|succeeded
    #  ignore_errors: yes

    #- name: Install Jupyter on Python 2
    #  pip:
    #    name: jupyter

    - name: Install Jupyter on Python 3
      shell: "pip3 install --upgrade jupyter"
      retries: 2
      register: result
      until: result|succeeded     

    #- name: remove julia
    #  apt:
    #    name: julia
    #    state: absent
    #  tags:
    #    - hack

    #- name: install julia
    #  apt:
    #    name: julia
    #  tags:
    #    - hack

    #- name: Install IJulia
    #  shell: |
    #    julia -e 'Pkg.add("IJulia");'

    - name: Copy systemd for jupyter-notebook
      copy:
        remote_src: true
        src: /storage/docker/systemd/jupyter.service
        dest: /etc/systemd/system

    - name: create notebooks directory
      file:
        path: /storage/docker/jupyter/notebooks
        mode: 0777
        state: directory

    - name: start and enable jupyter
      systemd:
        name: jupyter
        enabled: yes
        state: started

    - name: Install Ipython for Python 2
      pip:
        name: ipykernel
      retries: 2
      register: result
      until: result|succeeded
      ignore_errors: yes

    #- name: Install tensorflow
    #  shell: pip install https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.1.0/tensorflow-1.1.0-cp27-none-linux_armv7l.whl


    - name: Install Ipython2 kernel
      shell: python2 -m ipykernel install --user

    - name: Install Ipython3 kernel
      shell: python3 -m ipykernel install --user

    - name: Install bash_jupyter
      pip:
        name: bash_kernel

    - name: Install bash_kernel kernelspec
      shell: python -m bash_kernel.install 












